---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mleuv-secret
  namespace: mleuv
spec:
  encryptedData:
    AI_HUB_API_KEY: AgBtQMwWYx/QGn6GgxUpWajslJd5zvi+b3cVemxDqDalIsTPU93jemJp2d7KeCH+NCYQ7mcq9ai/Ubu9lMJepMfzYNt2hB6vZGyPoBumlvaMt05M46ELb+B8vgFTMb71c7KDECky5+/9zwQSRUaqwCRue3wQqim239823yuXYgEIYYiG4quCspRt6xQ/sG0Oq0xbeBwdbylzxnRWm9oXKlpIDCqeWUMgLKsq15TMAAL1OBh7s+qUWT2+2T30nSohQb4VTn7/VxShq69uqE9q3w9gYdZAbNTedc4/Np5aRPV/zlJO6/qxCDg9cMiOR6++nTR5FQwBAzusdOtIlyaD4xerzRSrViayZByyP60r0U8ZvRfoUocfV+OoPFRJ1Zof41UHGQm/DKmivcZhT5qcOlYW8P0PIMx3cdEJHZBiLGszu+FnigIFFItFABxIIwuX9MKMNzN+ayp4ujyJ/EkPLdPs9E5Jdk4n8fM/V0NGbZMNh7SDiqbl6ZO3vzy8A6p8ZlXy1fvUebISXuOL0M5l6pW/FnZOqNywCV6T6CF7OMkfGcVDZjIR/RccZl7K5hKohZuoJFmtqC1NCwIoo3dHMayW2E0YEU3se529zYAhz2or5riqB8mwAFBJxlWLGY+5Gp+mEhmKXlZqoIlJqQGoxZF7P08sNFzrbflN2e+3lIllkbbfILqwWY5b905U5t3PhNZ8RiI3lFc0UtYhr0Gl7dVrJgwtekJtWjhc
  template:
    metadata:
      creationTimestamp: null
      name: mleuv-secret
      namespace: mleuv
    type: Opaque
