apiVersion: v1
kind: Service
metadata:
  name: mleuv-qdrant
  labels:
    app: mleuv-qdrant
spec:
  type: ClusterIP
  selector:
    app: mleuv-qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
    - name: grpc
      port: 6334
      targetPort: 6334
