apiVersion: apps/v1
kind: Deployment
metadata:
  name: mleuv-web
  labels:
    app: mleuv-web
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mleuv-web
  template:
    metadata:
      labels:
        app: mleuv-web
    spec:
      containers:
        - name: web
          image: ghcr.io/aihpi/pilotproject-mleuv/web:sha-659e7cf
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
